server:
  port: 9001
  servlet:
    context-path: /zhangzhang-gateway

spring:
  application:
    name: zhangzhang-gateway
  cloud:
    nacos:
      #服务注册与发现
      discovery:
        enabled: true #如果不想使用 Nacos 作为注册中心的话赋值为false；
        server-addr: 127.0.0.1:8848 #nacos server地址
        #集群配置
        #server-addr: 127.0.0.1:8848,127.0.0.1:8858,127.0.0.1:8868
        namespace: 37ed5c88-0303-447a-a90e-89dbdea72207 #命名空间 nacos网页中创建的应用的命名空间
        #源数据
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
    # 静态路由
  #    gateway:
  #      routes:
  #        - id: path_route # 路由的ID
  #          uri: 127.0.0.1:8080/user/{id} # 匹配后路由地址
  #          predicates: # 断言, 路径相匹配的进行路由
  #            - Path=/user/{id}
  #  kafka:
  #    bootstrap-servers: 127.0.0.1:9092
  #    producer:
  #      retries: 3
  #    consumer:
  #      auto-offset-reset: latest
  #  zipkin:
  #    sender:
  #      type: kafka # 默认是 web
  #    base-url: http://localhost:9411/
  main:
    allow-bean-definition-overriding: true  # 因为将来会引入很多依赖, 难免有重名的 bean

# 这个地方独立配置, 是网关的数据, 代码 GatewayConfig.java 中读取被监听
nacos:
  gateway:
    route:
      config:
        data-id: zhangzhang-gateway
        group: zhangzhang

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
